name: Add Hacktoberfest Labels

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add Hacktoberfest labels to issues
        if: github.event_name == 'issues'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'hacktoberfest, hacktoberfest-accepted, hacktoberfest2024'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Hacktoberfest labels to PRs
        if: github.event_name == 'pull_request'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'hacktoberfest, hacktoberfest-accepted, hacktoberfest2024'
          github_token: ${{ secrets.GITHUB_TOKEN }}
